---
-
  hosts: deploy_routers
  become: true

  tasks:
    - name: install Dispatch Router
      block:
        - name: install Dispatch Router
          dnf: pkg={{item}} state=installed
          with_items:
            - qpid-dispatch-router
            - qpid-dispatch-tools

        - name: handle console
          block:
            - name: prepare to install console
              file:
                path: /usr/local/share/qpid-dispatch
                state: directory

            - name: archive the console
              local_action:
                module: archive
                dest: standalone.zip
                path: "{{playbook_dir}}/../../stand-alone"
                format: zip

            - unarchive:
                src: standalone.zip
                dest: /usr/local/share/qpid-dispatch

          when: create_console

        - name: create directories
          file:
            path: '{{ item }}'
            state: directory
          with_items:
            - /var/log/qdrouterd
            - /usr/local/etc/qpid-dispatch

      when: ansible_os_family == "RedHat"

    - name: Copying router configs
      copy:
        src: '../topologies/{{topology}}/{{item}}.conf'
        dest: /usr/local/etc/qpid-dispatch
      with_items: '{{ nodes }}'

    - name: stop running routers
      shell: "ps ax | grep qpid-dispatch/{{item}}.conf | grep -v 'grep' | awk -F ' ' '{print $1}' | xargs kill -9"
      #action: shell pkill -f qdrouterd
      ignore_errors: True
      with_items: '{{ nodes }}'

    - include_tasks: run_dispatch.yaml
      with_items: "{{ nodes }}"

