  - name: 'start router for {{item}}.conf'
    shell: "qdrouterd --config /usr/local/etc/qpid-dispatch/{{ item }}.conf -d"
    ignore_errors: True
    register: qdrouterd

  - name: 'force stop of {{item}}.conf'
    shell: "ps ax | grep qpid-dispatch/{{item}}.conf | grep -v 'grep' | awk -F ' ' '{print $1}' | xargs kill -9"
    ignore_errors: True
    when: qdrouterd.rc == 1

  - name: 'verify router for {{item}}.conf'
    shell: "ps aux | grep qpid-dispatch/{{item}}.conf | grep -v 'grep'"
    register: psresult
    ignore_errors: True

  - name: 'retry {{item}}.conf'
    shell: "qdrouterd --config /usr/local/etc/qpid-dispatch/{{ item }}.conf -d"
    when: psresult.rc == 1
